// <auto-generated />
using System;
using ChargePoint.CarManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChargePoint.CarManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260325172900_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("ChargePoint.CarManagement.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BienSo")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("HinhAnhBanGiaoKH")
                        .HasColumnType("TEXT");

                    b.Property<string>("HinhAnhNhanBanGiao")
                        .HasColumnType("TEXT");

                    b.Property<string>("MauXe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.Property<int>("OdoXe")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoLuong")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SoVIN")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("TEXT");

                    b.Property<int>("Stt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenKhachHang")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenXe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThongTinChoThue")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoBanGiaoKH")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoNhanBanGiao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BienSo = "30A-12345",
                            MauXe = "Đỏ",
                            NgayTao = new DateTime(2026, 3, 26, 0, 29, 0, 397, DateTimeKind.Local).AddTicks(723),
                            OdoXe = 15000,
                            SoLuong = 5,
                            SoVIN = "LVSHCAMB1NE000001",
                            Stt = 1,
                            TenKhachHang = "Nguyễn Văn A",
                            TenXe = "VinFast VF8",
                            ThongTinChoThue = "Xe cho thuê dài hạn"
                        },
                        new
                        {
                            Id = 2,
                            BienSo = "30B-67890",
                            MauXe = "Trắng",
                            NgayTao = new DateTime(2026, 3, 26, 0, 29, 0, 397, DateTimeKind.Local).AddTicks(727),
                            OdoXe = 8000,
                            SoLuong = 3,
                            SoVIN = "LVSHCAMB2NE000002",
                            Stt = 2,
                            TenKhachHang = "Trần Thị B",
                            TenXe = "VinFast VF9",
                            ThongTinChoThue = "Xe cho thuê ngắn hạn"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
