// <auto-generated />
using System;
using ChargePoint.CarManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChargePoint.CarManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260404075839_AddDOTImageToTireRecord")]
    partial class AddDOTImageToTireRecord
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("ChargePoint.CarManagement.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BienSo")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("MauBienSo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MauXe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.Property<int>("OdoXe")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrimaryImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("SoLuong")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SoVIN")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("TEXT");

                    b.Property<int>("Stt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenKhachHang")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenXe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThongTinChoThue")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BienSo = "30A-12345",
                            MauBienSo = 0,
                            MauXe = "Đỏ",
                            NgayTao = new DateTime(2026, 4, 4, 14, 58, 39, 61, DateTimeKind.Local).AddTicks(1812),
                            OdoXe = 15000,
                            SoLuong = 5,
                            SoVIN = "LVSHCAMB1NE000001",
                            Stt = 1,
                            TenKhachHang = "Nguyễn Văn A",
                            TenXe = "VinFast VF8",
                            ThongTinChoThue = "Xe cho thuê dài hạn"
                        },
                        new
                        {
                            Id = 2,
                            BienSo = "30B-67890",
                            MauBienSo = 0,
                            MauXe = "Trắng",
                            NgayTao = new DateTime(2026, 4, 4, 14, 58, 39, 61, DateTimeKind.Local).AddTicks(1815),
                            OdoXe = 8000,
                            SoLuong = 3,
                            SoVIN = "LVSHCAMB2NE000002",
                            Stt = 2,
                            TenKhachHang = "Trần Thị B",
                            TenXe = "VinFast VF9",
                            ThongTinChoThue = "Xe cho thuê ngắn hạn"
                        });
                });

            modelBuilder.Entity("ChargePoint.CarManagement.Models.CarMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("CarMedias");
                });

            modelBuilder.Entity("ChargePoint.CarManagement.Models.MaintenanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapBaoDuong")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ChiPhi")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("HinhAnhChungTu")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayBaoDuong")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgayBaoDuongTiepTheo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NoiBaoDuong")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NoiDungBaoDuong")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("SoKmBaoDuong")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SoKmBaoDuongTiepTheo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("MaintenanceRecords");
                });

            modelBuilder.Entity("ChargePoint.CarManagement.Models.TireRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ChiPhi")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("HangLop")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("HinhAnhChungTu")
                        .HasColumnType("TEXT");

                    b.Property<string>("HinhAnhDOT")
                        .HasColumnType("TEXT");

                    b.Property<string>("KichThuocLop")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("LoaiThaoTac")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelLop")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayThucHien")
                        .HasColumnType("TEXT");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NoiThucHien")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("OdoThayLop")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OdoThayTiepTheo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ViTriLop")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("TireRecords");
                });

            modelBuilder.Entity("ChargePoint.CarManagement.Models.TrafficViolationCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CoViPham")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayKiemTra")
                        .HasColumnType("TEXT");

                    b.Property<string>("NguoiKiemTra")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SoLuongViPham")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TongTienPhat")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("TrafficViolationChecks");
                });

            modelBuilder.Entity("ChargePoint.CarManagement.Models.CarMedia", b =>
                {
                    b.HasOne("ChargePoint.CarManagement.Models.Car", "Car")
                        .WithMany("Media")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("ChargePoint.CarManagement.Models.MaintenanceRecord", b =>
                {
                    b.HasOne("ChargePoint.CarManagement.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("ChargePoint.CarManagement.Models.TireRecord", b =>
                {
                    b.HasOne("ChargePoint.CarManagement.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("ChargePoint.CarManagement.Models.TrafficViolationCheck", b =>
                {
                    b.HasOne("ChargePoint.CarManagement.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("ChargePoint.CarManagement.Models.Car", b =>
                {
                    b.Navigation("Media");
                });
#pragma warning restore 612, 618
        }
    }
}
