// <auto-generated />
using System;
using ChargePoint.CarManagement.Infrastructure.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChargePoint.CarManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260502062108_AddSearchIndexes")]
    partial class AddSearchIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ChargePoint.CarManagement.Domain.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BienSo")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("BienSoCu")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("MauBienSo")
                        .HasColumnType("int");

                    b.Property<string>("MauXe")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("NgayHetHan")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("NgayThue")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("OdoXe")
                        .HasColumnType("int");

                    b.Property<string>("PrimaryImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("SoVIN")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("varchar(17)");

                    b.Property<int>("Stt")
                        .HasColumnType("int");

                    b.Property<string>("TenKhachHang")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TenXe")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ThongTinChoThue")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("BienSo")
                        .HasDatabaseName("idx_cars_bienso");

                    b.HasIndex("MauXe")
                        .HasDatabaseName("idx_cars_mauxe");

                    b.HasIndex("SoVIN")
                        .HasDatabaseName("idx_cars_sovin");

                    b.HasIndex("Stt")
                        .HasDatabaseName("idx_cars_stt");

                    b.HasIndex("TenKhachHang")
                        .HasDatabaseName("idx_cars_tenkhachhang");

                    b.HasIndex("TenXe")
                        .HasDatabaseName("idx_cars_tenxe");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BienSo = "30A-12345",
                            MauBienSo = 0,
                            MauXe = "Đỏ",
                            NgayTao = new DateTime(2026, 5, 2, 13, 21, 8, 295, DateTimeKind.Local).AddTicks(5019),
                            OdoXe = 15000,
                            SoLuong = 5,
                            SoVIN = "LVSHCAMB1NE000001",
                            Stt = 1,
                            TenKhachHang = "Nguyễn Văn A",
                            TenXe = "VinFast VF8",
                            ThongTinChoThue = "Xe cho thuê dài hạn"
                        },
                        new
                        {
                            Id = 2,
                            BienSo = "30B-67890",
                            MauBienSo = 0,
                            MauXe = "Trắng",
                            NgayTao = new DateTime(2026, 5, 2, 13, 21, 8, 295, DateTimeKind.Local).AddTicks(5024),
                            OdoXe = 8000,
                            SoLuong = 3,
                            SoVIN = "LVSHCAMB2NE000002",
                            Stt = 2,
                            TenKhachHang = "Trần Thị B",
                            TenXe = "VinFast VF9",
                            ThongTinChoThue = "Xe cho thuê ngắn hạn"
                        });
                });

            modelBuilder.Entity("ChargePoint.CarManagement.Domain.Entities.CarMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FileName")
                        .HasMaxLength(260)
                        .HasColumnType("varchar(260)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("CarMedias");
                });

            modelBuilder.Entity("ChargePoint.CarManagement.Domain.Entities.MaintenanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CapBaoDuong")
                        .HasColumnType("int");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<decimal>("ChiPhi")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("HinhAnhChungTu")
                        .HasColumnType("longtext");

                    b.Property<int>("LoaiHoSo")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBaoDuong")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NoiBaoDuong")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NoiDungBaoDuong")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("SoKmBaoDuong")
                        .HasColumnType("int");

                    b.Property<int?>("SoKmBaoDuongTiepTheo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("MaintenanceRecords");
                });

            modelBuilder.Entity("ChargePoint.CarManagement.Domain.Entities.SystemSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("Key");

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            Key = "AutoUpdateOdo_Tire",
                            Description = "Tự động cập nhật ODO của xe khi thêm hồ sơ lốp",
                            Type = "boolean",
                            Value = "false"
                        },
                        new
                        {
                            Key = "AutoUpdateOdo_Maintenance",
                            Description = "Tự động cập nhật ODO của xe khi thêm hồ sơ bảo dưỡng",
                            Type = "boolean",
                            Value = "false"
                        },
                        new
                        {
                            Key = "MaintenanceMode",
                            Description = "Bảo trì hệ thống (Chỉ root account mới được truy cập)",
                            Type = "boolean",
                            Value = "false"
                        });
                });

            modelBuilder.Entity("ChargePoint.CarManagement.Domain.Entities.TireRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<decimal>("ChiPhi")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("HangLop")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HinhAnhChungTu")
                        .HasColumnType("longtext");

                    b.Property<string>("HinhAnhDOT")
                        .HasColumnType("longtext");

                    b.Property<string>("KichThuocLop")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("LoaiThaoTac")
                        .HasColumnType("int");

                    b.Property<string>("ModelLop")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NgayThucHien")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NoiThucHien")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("OdoThayLop")
                        .HasColumnType("int");

                    b.Property<int?>("OdoThayTiepTheo")
                        .HasColumnType("int");

                    b.Property<int>("ViTriLop")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("TireRecords");
                });

            modelBuilder.Entity("ChargePoint.CarManagement.Domain.Entities.TrafficViolationCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<bool>("CoViPham")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("DiaDiemViPham")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("NgayCapNhatTrangThai")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("NgayGioViPham")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NgayKiemTra")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NguoiXuLy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NoiDungViPham")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("SoLuongViPham")
                        .HasColumnType("int");

                    b.Property<int>("TrangThaiXuLy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("TrafficViolationChecks");
                });

            modelBuilder.Entity("ChargePoint.CarManagement.Domain.Entities.CarMedia", b =>
                {
                    b.HasOne("ChargePoint.CarManagement.Domain.Entities.Car", "Car")
                        .WithMany("Media")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("ChargePoint.CarManagement.Domain.Entities.MaintenanceRecord", b =>
                {
                    b.HasOne("ChargePoint.CarManagement.Domain.Entities.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("ChargePoint.CarManagement.Domain.Entities.TireRecord", b =>
                {
                    b.HasOne("ChargePoint.CarManagement.Domain.Entities.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("ChargePoint.CarManagement.Domain.Entities.TrafficViolationCheck", b =>
                {
                    b.HasOne("ChargePoint.CarManagement.Domain.Entities.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("ChargePoint.CarManagement.Domain.Entities.Car", b =>
                {
                    b.Navigation("Media");
                });
#pragma warning restore 612, 618
        }
    }
}
